quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/vietnam_logistics

quarkus.flyway.migrate-at-start=true

# Kafka
kafka.bootstrap.servers=localhost:9092

# Kafka producer
mp.messaging.outgoing.supply-events.connector=smallrye-kafka
mp.messaging.outgoing.supply-events.topic=supply-events

# Kafka consumer
mp.messaging.incoming.supply-events-in.connector=smallrye-kafka
mp.messaging.incoming.supply-events-in.topic=supply-events
mp.messaging.incoming.supply-events-in.group.id=logistics
mp.messaging.incoming.supply-events-in.auto.offset.reset=earliest

# ElasticSearch
quarkus.elasticsearch.hosts=localhost:9200

# Disable scheduler for test profile
%test.quarkus.scheduler.enabled=false